/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package foodregister;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.sql.* ;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;




public class FoodJframe extends javax.swing.JFrame {

    /** Creates new form FoodJframe */
    public FoodJframe() {
        initComponents();
        nameTField = "tField";
        count = 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPannel = new javax.swing.JPanel();
        signinPannel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nameUserText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        labelShowId1 = new javax.swing.JLabel();
        userPassword = new javax.swing.JPasswordField();
        changeToSign1 = new javax.swing.JButton();
        buttpnRegister1 = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        registerPannel = new javax.swing.JPanel();
        confirmText = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        passwordText = new javax.swing.JLabel();
        passwordWrong = new javax.swing.JLabel();
        confirmField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        changeToSign = new javax.swing.JButton();
        buttpnRegister = new javax.swing.JButton();
        userPannel = new javax.swing.JPanel();
        signOut = new javax.swing.JButton();
        wordPannel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allPannel.setPreferredSize(new java.awt.Dimension(556, 342));
        allPannel.setLayout(new java.awt.CardLayout());

        jLabel5.setText("Name");

        jLabel6.setText("Password");

        userPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordActionPerformed(evt);
            }
        });

        changeToSign1.setText("Sign In ");
        changeToSign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeToSign1ActionPerformed(evt);
            }
        });

        buttpnRegister1.setText("Register");
        buttpnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttpnRegister1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signinPannelLayout = new javax.swing.GroupLayout(signinPannel);
        signinPannel.setLayout(signinPannelLayout);
        signinPannelLayout.setHorizontalGroup(
            signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPannelLayout.createSequentialGroup()
                .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinPannelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signinPannelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeToSign1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttpnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signinPannelLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(labelShowId1)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );
        signinPannelLayout.setVerticalGroup(
            signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPannelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeToSign1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttpnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(signinPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signinPannelLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(labelShowId1)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );

        allPannel.add(signinPannel, "card3");

        confirmText.setText("Confirm Password");

        nameText.setText("Name");

        passwordText.setText("Password");

        confirmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmFieldActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        changeToSign.setText("Sign In ");
        changeToSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeToSignActionPerformed(evt);
            }
        });

        buttpnRegister.setText("Register");
        buttpnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttpnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPannelLayout = new javax.swing.GroupLayout(registerPannel);
        registerPannel.setLayout(registerPannelLayout);
        registerPannelLayout.setHorizontalGroup(
            registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPannelLayout.createSequentialGroup()
                .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPannelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerPannelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(passwordWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(registerPannelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeToSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttpnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPannelLayout.setVerticalGroup(
            registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPannelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttpnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeToSign, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        allPannel.add(registerPannel, "card2");

        userPannel.setPreferredSize(new java.awt.Dimension(596, 344));

        signOut.setText("Sign Out");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wordPannelLayout = new javax.swing.GroupLayout(wordPannel);
        wordPannel.setLayout(wordPannelLayout);
        wordPannelLayout.setHorizontalGroup(
            wordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        wordPannelLayout.setVerticalGroup(
            wordPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPannelLayout = new javax.swing.GroupLayout(userPannel);
        userPannel.setLayout(userPannelLayout);
        userPannelLayout.setHorizontalGroup(
            userPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPannelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(wordPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        userPannelLayout.setVerticalGroup(
            userPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signOut)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(userPannelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(wordPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        allPannel.add(userPannel, "card4");

        getContentPane().add(allPannel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttpnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttpnRegisterActionPerformed
            // TODO add your handling code here:
            
        Connection conn = null;
        
        
        String name = nameTextField.getText();
        String password = String.valueOf(passwordField.getPassword());
        String confirm = String.valueOf(confirmField.getPassword());
        
        
        
        
        try {
        	System.out.println(CONN_STRING);
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            System.out.println("Connected");
            Statement stmt = (Statement) conn.createStatement();
            System.out.println(password);
            System.out.println(confirm);
            if (name.isEmpty() || password.isEmpty() || confirm.isEmpty() ){
                passwordWrong.setText("You need to fill out the field");
                
            }
            else if (confirm.equals(password)){
                String insert = "INSERT INTO tblCustomer ( name, password) VALUES ('"+name+"','"+password+"')";  
                stmt.executeUpdate(insert);
            
                confirmField.setText("");
                nameTextField.setText("");
                passwordField.setText("");
                passwordWrong.setText("Congratulation!");
                
                String table = name + "Table";
                System.out.println(table);
                String createTable = "CREATE TABLE "+table+" " +
                   "(id  INT(5) ZEROFILL not NULL , " +
                   " food VARCHAR(100), " + 
                   " type VARCHAR(255), " + 
                   " description VARCHAR(255), " + 
                   " date VARCHAR(30), " + 
                   " expired VARCHAR(30), " + 
                   " PRIMARY KEY ( id ))"; 
                System.out.println(createTable);

                stmt.executeUpdate(createTable);
                System.out.println("Created table in given database...");
                
                
                
            }else{
                confirmField.setText("");
                passwordWrong.setText("Your confirm password is wrong!!!!");
                
            }
            

            
        

            } catch(SQLException e){
                     if(e.getErrorCode() == 1062 ){
                           confirmField.setText("");
                           nameTextField.setText("");
                           passwordField.setText("");
                           System.out.println("same username");
                           passwordWrong.setText("This USERNAME already has!!!");
             }else{
                     System.err.print(e);
                     }
            }

         
    }//GEN-LAST:event_buttpnRegisterActionPerformed

    private void confirmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmFieldActionPerformed
        // TODO add your handling code here:
         
         confirmField.setEchoChar((char)0);
         confirmField.setEchoChar('#');

    }//GEN-LAST:event_confirmFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
         
        passwordField.setEchoChar((char)0);
        passwordField.setEchoChar('#');
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void userPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordActionPerformed
        // TODO add your handling code here:
        userPassword.setEchoChar('#');
    }//GEN-LAST:event_userPasswordActionPerformed

    private void buttpnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttpnRegister1ActionPerformed
        // TODO add your handling code here:
        allPannel.removeAll();
        allPannel.add(registerPannel);
        allPannel.repaint();
        allPannel.revalidate();  
    }//GEN-LAST:event_buttpnRegister1ActionPerformed

    private void changeToSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeToSignActionPerformed
        // TODO add your handling code here:
        
        allPannel.removeAll();
        allPannel.add(signinPannel);
        allPannel.repaint();
        allPannel.revalidate();
    }//GEN-LAST:event_changeToSignActionPerformed

    private void changeToSign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeToSign1ActionPerformed
    
        // TODO add your handling code here:
        Connection conn = null;
        String name = nameUserText.getText();
        String userpassword = String.valueOf(userPassword.getPassword());
        String confirmPassword = "";

        
        
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            System.out.println("Connected");
            Statement stmt = (Statement) conn.createStatement();
            String query = "SELECT * FROM users";
            String sql="SELECT password FROM tblCustomer WHERE tblCustomer.name='"+ name+"'";
            ResultSet rs = stmt.executeQuery(sql);
            //System.out.println(rs);
            
            if (rs.next() == false){
                warningLabel.setText("Couldn't find your account");
                //System.out.println(" no user name");
            }
            else{
                confirmPassword = rs.getString("password");
                //System.out.println(confirmPassword + "\n");
            }
            
            while (rs.next()) {
                 confirmPassword = rs.getString("password");
                 //System.out.println(confirmPassword + "\n");
            }
            
            System.out.println(userpassword + "\n");
            if (userpassword.isEmpty() || confirmPassword.isEmpty()){
                warningLabel.setText("Wrong password or account. Try again.");

                //System.out.println("please fill out the field");
            }
            else if (userpassword.equals(confirmPassword)){
                //System.out.println("Same Password");
                
                    userName = name;
                    allPannel.removeAll();
                    allPannel.add(userPannel);                    
                    allPannel.repaint();
                    allPannel.revalidate();  
                    
                    userDetail();
                
                
            }else{
              warningLabel.setText("Wrong password or account. Try again.");       
            }
            
                         
          

        
  
            } catch(SQLException e){
     
                     System.err.print(e);
    
            } catch (IOException ex) {
            Logger.getLogger(FoodJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
      
    }//GEN-LAST:event_changeToSign1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.out.println(userName);
        Connection conn = null;
        String userTable = userName + "Table";
        System.out.println(userTable);
        
        String confirmPassword = "";

        
        
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            System.out.println("Connected");
            Statement stmt = (Statement) conn.createStatement();
            //String query = "SELECT * FROM users";
            String sql="SELECT * FROM " + userTable + " WHERE id > 0";
            ResultSet rs = stmt.executeQuery(sql);
            //System.out.println(rs);
            
//            if (rs.next() == false){
//                warningLabel.setText("Couldn't find your account");
//                //System.out.println(" no user name");
//            }
//            else{
//                confirmPassword = rs.getString("password");
//                //System.out.println(confirmPassword + "\n");
//            }


            wordPannel.removeAll();
            
            while (rs.next()) {
                nameTField = rs.getString("food");
                
                
                System.out.println(nameTField);

                tLabel = new javax.swing.JLabel();
        
                tLabel.setSize(300, 30);
                tLabel.setLocation( 10, 40* count);

                tLabel.setText(nameTField  );
                count++;
                wordPannel.add(tLabel);

                wordPannel.revalidate();  // For JDK 1.7 or above.
                wordPannel.repaint();
                  
                 //System.out.println(confirmPassword + "\n");
            }
            } catch(SQLException e){
                     System.err.print(e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void userDetail() throws IOException{
         System.out.println(userName);
        Connection conn = null;
        String userTable = userName + "Table";
        System.out.println(userTable);
        
        String confirmPassword = "";

        
        
        try {
            conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            System.out.println("Connected");
            Statement stmt = (Statement) conn.createStatement();
            //String query = "SELECT * FROM users";
            String sql="SELECT * FROM " + userTable + " WHERE id > 0";
            ResultSet rs = stmt.executeQuery(sql);
            //System.out.println(rs);
            
//            if (rs.next() == false){
//                warningLabel.setText("Couldn't find your account");
//                //System.out.println(" no user name");
//            }
//            else{
//                confirmPassword = rs.getString("password");
//                //System.out.println(confirmPassword + "\n");
//            }


            wordPannel.removeAll();
            count = 1; 
            
            while (rs.next()) {
                
               
                System.out.println(rs.getString("imageURL"));
                
                URL img = new URL(rs.getString("imageURL"));
                javax.swing.ImageIcon image = new javax.swing.ImageIcon(img);
                javax.swing.JLabel label = new javax.swing.JLabel("", image, javax.swing.JLabel.CENTER);
               
               // allPannel.removeAll();   
                label.setSize(100, 75);
                label.setLocation(110 ,10 + 100* (count-1) );
                wordPannel.add(label);
                wordPannel.revalidate();  // For JDK 1.7 or above.
                wordPannel.repaint();
                
                nameTField = rs.getString("food");
                System.out.println(nameTField);

                tLabel = new javax.swing.JLabel();
        
                tLabel.setSize(300, 30);
                tLabel.setLocation( 10, 40* count);

                tLabel.setText(nameTField  );
                count++;
                wordPannel.add(tLabel);

                wordPannel.revalidate();  // For JDK 1.7 or above.
                wordPannel.repaint();
                  
                
                

                
                
                 //System.out.println(confirmPassword + "\n");
            }
            
//                URL img = new URL("https://imgur.com/30Jqvzm.jpg");
//                javax.swing.ImageIcon image = new javax.swing.ImageIcon(img);
//                javax.swing.JLabel label = new javax.swing.JLabel("", image, javax.swing.JLabel.CENTER);
//               
//               // allPannel.removeAll();   
//                label.setSize(100, 75);
//                label.setLocation(10,10);
//                wordPannel.add(label);
//                
//                wordPannel.revalidate();  // For JDK 1.7 or above.
//                wordPannel.repaint();
                
                
                
            } catch(SQLException e){
                     System.err.print(e);
            }
        
        
    }
    
    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        // TODO add your handling code here:

        allPannel.removeAll();
        allPannel.add(signinPannel);
        allPannel.repaint();
        allPannel.revalidate();

    }//GEN-LAST:event_signOutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPannel;
    private javax.swing.JButton buttpnRegister;
    private javax.swing.JButton buttpnRegister1;
    private javax.swing.JButton changeToSign;
    private javax.swing.JButton changeToSign1;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JLabel confirmText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelShowId1;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameUserText;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JLabel passwordWrong;
    private javax.swing.JPanel registerPannel;
    private javax.swing.JButton signOut;
    private javax.swing.JPanel signinPannel;
    private javax.swing.JPanel userPannel;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JPanel wordPannel;
    // End of variables declaration//GEN-END:variables


    
    
    private static  final String USERNAME= "   ";
    private static final String PASSWORD= "   ";
    private static final String CONN_STRING = "jdbc:mysql://sql3.freemysqlhosting.net/sql3197801";
            
    
    
    private javax.swing.JLabel tLabel;
    private String nameTField;
    private int count;
    private String userName;
}
